### ISSUE TITLE
Capstone exercise

### ISSUE THREAD

**Issue by karawoo** [karawoo/2015-04-27-wsu#15]
We're planning to do a capstone exercise similar to [the one Naupaka used](https://github.com/naupaka/2015-02-21-iplant/blob/gh-pages/workshop/02_Sunday/02_Sunday_pm/Readme_exercise.md) at iPlant. I propose something like this:
### Using an Rmd file, create a short analysis report using R of the gapminder dataset.
1. Pick three countries you are interested in
2. Write an Rmd script to load the gapminder data file, select all the data for that country (hint, use the `filter()` function), and use ggplot to make a three scatter plots (one for each country) that has year on the x-axis and GDP on the y axis. Make sure you load all the libraries you might need (dplyr, ggplot2, etc). Describe any trends you see for each country using markdown text.
3. Commit the changes to your .Rmd file using git.
4. For the year 2007, calculate the mean, min, and max life expectancies for each continent. Describe what you see in the results using markdown text.
5. Commit your changes using git and push them to GitHub.
6. Make 2 histograms of global life expectancy using ggplot. One with the default bin widths and one with narrower bin widths. Explain the differences and any interesting trends in markdown text.
7. Commit your changes and push them to GitHub.
8. Compile the final .Rmd file to HTML, make sure it looks ok, and then commit this HTML file (plus figures) and push everything to GitHub.

Comments and suggestions are very welcome.

**Comment by kbroman** [comment]
Awesome! I like it.

**Comment by kbroman** [comment]
Added in PR #26.
