### ISSUE TITLE
Cheat sheets

### ISSUE THREAD

**Issue by kbroman** [karawoo/2015-04-27-wsu#16]
It might be good to identify or create cheat sheets for each part, and maybe bring copies for all of the students.

RStudio has a bunch of [good ones](http://www.rstudio.com/resources/cheatsheets/):
- [dplyr](http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
- [ggplot2](http://www.rstudio.com/wp-content/uploads/2015/04/ggplot2-cheatsheet.pdf)
- [R Markdown](http://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

Also need
- unix
- git

**Comment by kbroman** [comment]
Github has a good one for [git](https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf).
Or there's [this one](http://www.git-tower.com/blog/git-cheat-sheet/).

[This one](http://files.fosswire.com/2007/08/fwunixref.pdf) seems good for unix.
Or [this one](http://www.cheatography.com/davechild/cheat-sheets/linux-command-line/pdf/).

**Comment by kbroman** [comment]
I've printed 38 copies of each and will bring them along. (I count 34 students + 2 helpers + 2 instructors; 34 is probably sufficient but...)

**Comment by karawoo** [comment]
Thanks, Karl!
