### ISSUE TITLE
Where are the lessons?

### ISSUE THREAD

**Issue by bw4sz** [karawoo/2015-04-27-wsu#52]
Hi @karawoo !

I'm teaching a git lesson at the Data Carpentry event here in portland, and i wanted to start by merging the we lesson you and Karl taught in Pullman. I know that this repo creates the github pages, and i'm just having a little trouble finding where the lesson is. I remember you had slides that rendered in the browser? If you could just help orient me, i can work from there.

Thanks!

**Comment by bw4sz** [comment]
I realized the lessons are in their own repo. Do not let me know if you made slides for them, of how you went about modifying them, but i'll close.

**Comment by kbroman** [comment]
There's a [`Makefile`](https://github.com/karawoo/2015-04-27-wsu/tree/gh-pages/syllabus/Makefile) in the [`syllabus`](https://github.com/karawoo/2015-04-27-wsu/tree/gh-pages/syllabus) directory that converts the `.Rmd` and `.md` files into html.

I think you type `make preview`. You may need to install a bunch of python modules.

Inside the [`slides`](https://github.com/karawoo/2015-04-27-wsu/tree/gh-pages/syllabus/slides) subdirectory, there's another [`Makefile`](https://github.com/karawoo/2015-04-27-wsu/tree/gh-pages/syllabus/slides/Makefile) that uses a ruby script, [`grab_challenges.rb`](https://github.com/karawoo/2015-04-27-wsu/tree/gh-pages/syllabus/slides/grab_challenges.rb), to pull out the challenges from the `.Rmd` and `.md` files and put them into html-based slides. It's _quite_ rough.
