### ISSUE TITLE
Where to put the data?

### ISSUE THREAD

**Issue by kbroman** [karawoo/2015-04-27-wsu#9]
We can grab the gapminder data from the [gapminder](https://github.com/jennybc/gapminder) package as follows:

``` r
if(!require(gapminder)) {
    install.packages("gapminder")
    library(gapminder)
}
write.csv(gapminder, "gapminder.csv", row.names=FALSE)
```

But where should I put the file?

**Comment by karawoo** [comment]
Do you mean for learners to download, or for us to use in our RMarkdown lessons?

**Comment by kbroman** [comment]
Either one. For learners, it'd be best to have a very short URL.

**Comment by karawoo** [comment]
How about adding it to the syllabus directory I created in #5? I can do this and then go ahead and merge. We can use bit.ly later to shorten the URL for student downloading. Sound ok?

**Comment by kbroman** [comment]
ok, sounds good.

I was thinking of using `read.csv("http:// ... /blah.csv")` to load the file, and I don't think that'll work with a bit.ly link, but I guess we can just download the file and then load it. Students often have trouble finding the file once downloaded, but that's a good skill to help them with.

**Comment by karawoo** [comment]
Oh yeah, I was thinking the bit.ly link would be to download the data and then they'd load it with `read.csv()`. It'll be good to explain how to load files that are on their computers I think, since that is probably how they work with their own data. I'll add the gapminder data and merge #5.
